### ISSUE TITLE
Inputs looks broken

### ISSUE THREAD

**Issue by Akiyamka** [opium-pro/themeor#1]
![image](https://user-images.githubusercontent.com/6587585/128223603-8b7c2684-926e-4d55-b387-2bcdab78b7a0.png)
Firefox 90.0.2
Chrome 92.0.4515.131

**Comment by elianovsky** [comment]
Hello. Thank you. Fixed in version `1.0.6`
By default 'Box' has to set `background-color: transparent` if `fill` is not specified.
But in versions `1.0.1 — 1.0.4` was a bug when it just left the default color (color of default input background in your case)
